name: Demonstrate caching

on:
  - push

env:
  PYTHON_VERSION: "3.9"                 # set this to the python version to use (supports 3.6, 3.7, 3.8)

jobs:
  test-pip:
    runs-on: ubuntu-latest
    steps:

    - name: "Checkout GitHub Action"
      uses: actions/checkout@v2

    - name: Setup Python ${{ env.PYTHON_VERSION }} Environment
      uses: actions/setup-python@v2
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        cache: 'pip'
        cache-dependency-path: 'requirements/*.txt'
    - run: python -m pip install -r requirements/test.txt

    - name: Use pandas
      run: python -c "import pandas"

  test-pip-again:
    needs: test-pip
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout GitHub Action"
      uses: actions/checkout@v2

    - name: Setup Python ${{ env.PYTHON_VERSION }} Environment
      uses: actions/setup-python@v2
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        cache: 'pip'
        cache-dependency-path: 'requirements/*.txt'
    - run: python -m pip install -r requirements/test.txt

    - name: Use pandas
      run: python -c "import pandas"