# This workflow will update something in the repo, stage it, commit it, and push it

name: Update the repo with changes from the action


on: workflow_dispatch

env:
  BRANCH_NAME: update-timestamp
  OUTPUT_NAME: now.txt

jobs:
  update-repo:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"

    - name: Setup git
      run: |
        git config user.name "GitHub Actions Automation"
        git config user.email "<>"
        git checkout ${BRANCH_NAME} 2>/dev/null || git checkout -b ${BRANCH_NAME}

    - name: Update the random number
      run: python update_timestamp.py --file ${OUTPUT_NAME}

    

    - name: Update the repo
      run: |
        git add ${OUTPUT_NAME}
        git commit -m "Updated the file from a Github Action"
        git push origin ${BRANCH_NAME}