# This should only trigger for changes to main

# No need to run unit tests
# How can we validate that the creds and infrastructure exist?

name: Production only
on:
  push:
    branches:
      - master
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello Production World!"