# This should trigger for changes to "dev" branches (not production and not staging)

# Run unit tests, run integration tests in labs env

name: Everything besides prod and staging
on:
  push:
    branches:
      - '*'
      - '!staging'
      - '!master'
      - '!main'

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Run Unit Tests
        run: echo "Running unit tests"

  validate-infrastructure:
    needs: unit-tests
    needs: validate-secrets
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: Validate required infrastructure
        run: echo "Running Python script to validate infra ..."

  integration-tests:
    needs: validate-infrastructure
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: Run Integration Tests
        run: echo "Running integration tests"
