# This should trigger for changes to "dev" branches (not production and not staging)

# Run unit tests, run integration tests in labs env

name: Everything besides prod and staging
on:
  push:
    branches:
      - '*'
      - '!staging'
      - '!master'

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello Some Branch World!"