# This should only trigger for changes to the staging branch

# No need to run unit tests
# How can we validate that the creds and infrastructure exist?

name: Staging Only
on:
  push:
    branches:
      - staging

jobs:
  test-secrets:
    runs-on: ubuntu-latest
    environment: staging  # Set the `environment` key to use 
    steps:
      - name: Check if secret exists
        env:
          STAGING_SECRET: ${{ secrets.STAGING_SECRET }}
        if: env.STAGING_SECRET == null
        run: exit 1
        
      - name: Staging secret
        run: echo "You should see three asterisks \"${{ secrets.STAGING_SECRET }}\""

      - name: Production secret
        env:
          PROD_SECRET: ${{ secrets.PROD_SECRET }}
        if: env.PROD_SECRET == null
        run: echo "Product secret is inaccessible"
