# This should only trigger for changes to the staging branch

# No need to run unit tests
# How can we validate that the creds and infrastructure exist?

name: Staging Only
on:
  push:
    branches:
      - staging
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Get secret
        env:
          STAGING_SECRET: ${{ secrets.STAGING_SECRET }}
        run: echo "Hello Staging World! Your secret is $STAGING_SECRET"

      - name: Secret fail
        env:
          FAILED_SECRET: ${{ secrets.PROD_SECRET }}
        run: echo "Can't see this one $FAILED_SECRET"
