# This should only trigger for changes to the staging branch

# No need to run unit tests
# How can we validate that the creds and infrastructure exist?

name: Staging Only
on:
  push:
    branches:
      - staging
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Get secret
        with: # Set the secret as an input
          super_secret: ${{ secrets.STAGING_SECRET }}
        
      - name: Do Step
        run: echo "Hello Staging World!"
