# This should only trigger for changes to the staging branch

# No need to run unit tests
# How can we validate that the creds and infrastructure exist?

name: Staging Only
on:
  push:
    branches:
      - staging

jobs:
  test-secrets:
    runs-on: ubuntu-latest
    environment: staging  # Set the `environment` key to use 
    steps:
      - name: Staging secret
        run: echo "You should see three asterisks \"${{ secrets.STAGING_SECRET }}\""

      - name: Production secret
        run: echo "You will see an empty string \"${{ secrets.PROD_SECRET }}\""
